#!/usr/bin/env node
// Inline public/ into src/ui.generated.ts so a deploy is one artifact.
// Source of truth stays public/ (editable, testable); run this after edits.
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const publicDir = join(root, "public");
const files = readdirSync(publicDir).filter((f) => !f.startsWith(".")).sort();

const typeFor = (f) =>
  f.endsWith(".html") ? "text/html; charset=utf-8"
  : f.endsWith(".js") ? "text/javascript; charset=utf-8"
  : f.endsWith(".css") ? "text/css; charset=utf-8"
  : "application/json";

const entries = files.map((f) => {
  const body = readFileSync(join(publicDir, f), "utf8");
  return `  ${JSON.stringify(`/${f}`)}: { body: ${JSON.stringify(body)}, type: ${JSON.stringify(typeFor(f))} },`;
});

const out = `// Generated by scripts/build-ui.mjs — do not edit. Source: public/.
export const UI_ASSETS: Record<string, { body: string; type: string }> = {
${entries.join("\n")}
};
`;
writeFileSync(join(root, "src/ui.generated.ts"), out);
console.log(`build-ui: ${files.length} files inlined`);
